baseurl = "http://ioos.github.io/sos-guidelines"
CanonifyUrls = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
languageCode = "en-us"
[params]
  Title = "IOOS SOS Guidelines"
  Tagline = "Docs, codes, scripts, templates"
[params.Github]
  Head = "master"
  Url = "https://github.com/ioos/sos-guidelines"
	
	
 
